SGT/urls.py
# Django
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import re_path
import notifications.urls
from django.urls import reverse_lazy

urlpatterns = [
                  path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
                  path('archivo/', include(('file.urls', 'file'), namespace='archivo')),
                  path('usuario/', include(('usuario.urls', 'usuario'), namespace='usuario')),
                  path('prueba',
                       TemplateView.as_view(template_name='prueba.html')
                       ),
                  path('reset/password_reset', PasswordResetView.as_view(
                      template_name='registration/password_reset_form.html',
                      email_template_name="registration/password_reset_email.html"),
                       name='password_reset'),
                  path('reset/password_reset_done',
                       PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
                       name='password_reset_done'),
                  re_path(r'^reset/(?P<uidb64>[0-9A-za-z_\-]+)/(?P<token>.+)/$',
                          PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
                          name='password_reset_confirm'),
                  path('reset/done',
                       PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
                       name='password_reset_complete')

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

file/urls.py
"""URL's de importe del archivo"""

# Django
from django.urls import path

# Views
import file.views as ImporteControl
from file import views

# Filtros

urlpatterns = [
    path(
        route='importe/',
        view=ImporteControl.upload_excel,
        name='importe'
    ),
    path(
        route='entregar/',
        view=views.ListarArchivo.as_view(),
        name='listar_llamada'
    ),
    path(
        route='asignar/',
        view=views.registro_llamada,
        name='asignar'
    ),
    path(
        route='realizar/',
        view=views.registro_llamada,
        name='registrar_llamada'
    ),
    path(
        route='buzon/',
        view=views.realizar_llamada,
        name='buzon'
    ),
    path(
        route='repartir/',
        view=views.repartir,
        name='repartir'
    ),
    path(
        route='enviar',
        view=views.enviarLlamadas,
        name='enviarLlamada'
    ),
    path(
        route='entregar_l/',
        view=views.entregar.as_view(),
        name='entregar_l'
    ),
    path(
        route='entrega',
        view=views.ver_Llamadas,
        name='entrega'
    ),
    path(
        route='eliminar',
        view=views.archivoLlamadas.as_view(),
        name='eliminar'
    ),
    path(
        route='borrar',
        view=views.eliminarArchivo,
        name='exterminar'
    ),
    path(
        route='traer',
        view=views.traer,
        name='traer'
    ),
    path(
        route='ListFile',
        view=views.search,
        name='ListFile'
    ),
    path(
        route='verllamadas',
        view=views.ver_Llamadas,
        name='borrar'
    ),
    path(
        route='prueballamadas',
        view=views.pruebas_llamadas,
        name='prueballamada'
    ),
    path(
        route='prueba/<int:number>/',
        view=views.realizar_llamada,
        name='prueba'
    ),
    path(
        route='listfile',
        view=views.ListFile,
        name='listFile'
    ),
    path(
        route='create_estado',
        view=views.CrearEstado.as_view(),
        name='estado'
    ),

    path(
        route='update_estado',
        view=views.ActualizarEstado.as_view(),
        name='UpdateEstado'

    ),

    # esta ruta me retorna solo un template "reporte llamadas"
    path(
        route='reporte_llamada/',
        view=views.reporte_llamada,
        name='reporte_llamada'
    ),
    # esta ruta solo es para llevarle lo solicitado a el template"reporte llamadas"
    path(
        route='llevar_reporte_llamada',
        view=views.traer_reporte_llamada,
        name='llevar_reporte_llamada'
    ),
    # esta ruta me lleva a el metodo donde se exporta para aceb
    path(
        route='completo',
        view=views.reporte_general,
        name='completo'
    ),
    # esta ruta me retorna los datos en el template "reporte general"
    path(
        route='envio_general',
        view=views.trer_reporte_general,
        name='envio_general'
    ),
    # esta ruta me retorna solo un template "reporte usuario"
    path(
        route='reporte_usuario',
        view=views.reporte_usuario,
        name='reporte_usuario'
    ),
    # esta ruta es para llevarle lo solicitado a el template"reporte usuario"
    path(
        route='traer_reporte_usuario',
        view=views.traer_reporte_usuario,
        name="traer_reporte_usuario"
    ),
    path(
        route='liquidacion_usuario',
        view=views.liquidacion_operador,
        name='liquidacion_usuario'
    ),
    path(
        route='llevar_liquidacion',
        view=views.llevar_liquidacion,
        name='llevar_liquidacion'
    )
]

templates/reportes/liquidacion.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}
    <head>
        <link rel="icon" type="image/png" sizes="192x192" href="{% static 'dist/img/LogoSGT.png' %}">
        <title>Mi Reporte</title>
        <script src="{% static 'dist/jquery/dist/jquery.min.js' %}"></script>
        <script src="{% static 'dist/Datatables/FileSaver.min.js' %}"></script>
        <script src="{% static 'dist/Datatables/xlsx.full.min.js' %}"></script>
        <link rel="stylesheet" href="{% static 'dist/bootstrap/dist/css/bootstrap.min.css' %}">

    </head>
{% endblock %}

{% block main %}
    <div class="container card-sm bg-white" style="border-radius: 5px">

        <h3 class="hk-pg-title mt-2">
            <i class="fas fa-hand-holding-usd"></i> Liquidaciones
            <button class="btn btn-outline-success float-lg-right col-sm-3" id="button-a" data-toggle="tooltip"
                    data-placement="top" title="Exportar excel">
                Exportar
            </button>
        </h3>

        <hr>
        <div class="row mt-4 card-body">
            <div class="col">
                <table class="tablesaw  tablesaw-bar table-hover" id="table">
                    <thead class="table-borderless">
                    <tr>
                        <th scope="col">Nombre Operador</th>
                        <th scope="col">Total llamadas</th>
                        <th scope="col">Total liquidado</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr class="tablesaw-sortable-arrow table-info">
                        <td>{{ nombre }}</td>
                        <td>{{ total }}</td>
                        <td>{{ consulta.suma }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class="col">
                <form method="post" action="{% url 'archivo:llevar_liquidacion' %}">
                    {% csrf_token %}
                    <div class="container ">
                        <div class="row">
                            <div class="col-sm-8">
                                <strong>Meses</strong>
                                <select name="meses" class="form-control">
                                    <option value="1">Enero</option>
                                    <option value="2">Febrero</option>
                                    <option value="3">Marzo</option>
                                    <option value="4">Abril</option>
                                    <option value="5">Mayo</option>
                                    <option value="6">Junio</option>
                                    <option value="7">Julio</option>
                                    <option value="8">Agosto</option>
                                    <option value="9">Septiembre</option>
                                    <option value="10">Octubre</option>
                                    <option value="11">Noviembre</option>
                                    <option value="12">Diciembre</option>
                                </select>
                            </div>
                            <div class="col">
                                <button type="submit" class="btn btn-outline-info mt-4"><i class="fas fa-search"></i> Buscar
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="hk-footer-wrap container">
        <footer class="footer">
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <p>Creado por<a href="https://hencework.com/" class="text-dark" target="_blank">La Gerencia</a>
                        © 2019</p>
                </div>
                <div class="col-md-6 col-sm-12">
                    <p class="d-inline-block">Follow us</p>
                    <a href="#" class="d-inline-block btn btn-icon btn-icon-only btn-indigo btn-icon-style-4"><span
                            class="btn-icon-wrap"><i class="fa fa-facebook"></i></span></a>
                    <a href="#" class="d-inline-block btn btn-icon btn-icon-only btn-indigo btn-icon-style-4"><span
                            class="btn-icon-wrap"><i class="fa fa-twitter"></i></span></a>
                    <a href="#" class="d-inline-block btn btn-icon btn-icon-only btn-indigo btn-icon-style-4"><span
                            class="btn-icon-wrap"><i class="fa fa-google-plus"></i></span></a>
                </div>
            </div>
        </footer>
    </div>
    {% block javascript %}
        <script>


            function excel_exporte() {
                var wb = XLSX.utils.table_to_book(document.getElementById('table'), {sheet: "Sheet JS"});
                var wbout = XLSX.write(wb, {bookType: 'xlsx', bookSST: true, type: 'binary'});
                return wbout
            }


            function s2ab(s) {
                var buf = new ArrayBuffer(s.length);
                var view = new Uint8Array(buf);
                for (var i = 0; i < s.length; i++) view[i] = s.charCodeAt(i) & 0xFF;
                return buf;
            }

            $("#button-a").click(function () {

                Swal.fire({
                    title: 'Desea exportar los datos?',
                    text: "Verifique los datos de la tabla!",
                    icon: 'info',
                    showCancelButton: true,
                    confirmButtonColor: '#36876a',
                    cancelButtonColor: '#409ec1',
                    confirmButtonText: 'Si deseo exportar!'
                }).then((result) => {
                    if (result.value) {
                        saveAs(new Blob([s2ab(excel_exporte())], {type: "application/octet-stream"}), 'Telemercadeo.xlsx');
                        Swal.fire(
                            'Exportado!',
                            'Su reporte esta listo',
                            'success'
                        )
                    }
                })
            });

            var español = {
                "sProcessing": "Procesando...",
                "sLengthMenu": "Mostrar _MENU_ Registros",
                "sZeroRecords": "No se encontraron resultados",
                "sEmptyTable": "Ningún dato disponible en esta tabla",
                "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "sInfoThousands": ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst": "Primero",
                    "sLast": "Último",
                    "sNext": "Siguiente",
                    "sPrevious": "Anterior"
                },
                "oAria": {
                    "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                },
                "buttons": {
                    "copy": "Copiar",
                    "colvis": "Visibilidad"
                }
            };
        </script>
    {% endblock %}
{% endblock %}

templates/reportes/reporte_general.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}
    <head>
        <link rel="icon" type="image/png" sizes="192x192" href="{% static 'dist/img/LogoSGT.png' %}">
        <title>Exportar</title>
        <script src="{% static 'dist/jquery/dist/jquery.min.js' %}"></script>
        <script src="{% static 'dist/Datatables/FileSaver.min.js' %}"></script>
        <script src="{% static 'dist/Datatables/xlsx.full.min.js' %}"></script>
        <link rel="stylesheet" href="{% static 'dist/bootstrap/dist/css/bootstrap.min.css' %}">

    </head>
{% endblock %}

{% block main %}
    <div class="container card-sm bg-white" style="border-radius: 5px">

        <h3 class="hk-pg-title mt-2">
            <i class="fa fa-search"></i> Reportes
            <button class="btn btn-outline-success float-lg-right col-sm-3" id="button-a" data-toggle="tooltip"
                    data-placement="top" title="Exportar excel">
                Exportar
            </button>
        </h3>

        <hr>
        <form method="post" action="{% url 'archivo:envio_general' %}">
            {% csrf_token %}
            <div class="container ">
                <div class="row card-body">
                    <div class="col-sm-3">
                        <select name="respuesta" class="form-control">
                            <option value="0">Desde siempre</option>
                            <option value="1">Ultimo dia</option>
                            <option value="2">Ultima semana</option>
                            <option value="3">Ultimo mes</option>
                            <option value="4">Ultimo archivo</option>
                        </select>

                    </div>

                    <div class="col-sm-3">
                        <select name="realizado1" class="form-control">
                            <option value="0">Llamadas realizadas</option>
                            <option value="1">Todas las llamadas</option>
                        </select>
                    </div>
                    <div class="col-sm">
                        <button class="btn btn-outline-info ml-4" data-toggle="tooltip" data-placement="top"
                                title="Buscar datos" type="submit">Buscar
                        </button>
                    </div>
                </div>
            </div>
        </form>
        <table class="tablesaw  tablesaw-bar table-hover " id="table">
            <thead class="table-borderless">
            <tr>
                <th scope="col">Solicitante</th>
                <th scope="col">Ruta</th>
                <th scope="col">Cantidad</th>
                <th scope="col">Barrio</th>
                <th scope="col">Localidad</th>
                <th scope="col">Material</th>
                <th scope="col">Destinatario</th>
                <th scope="col">Telefono</th>
                <th scope="col" data-toggle="tooltip"
                    data-placement="top" title="Nombre contesta">Contesta
                </th>
                <th scope="col" data-toggle="tooltip"
                    data-placement="top" title="Fecha de Entrega ">Fecha
                </th>
                <th scope="col">Audio</th>
                <th scope="col">Estado</th>
            </tr>
            </thead>
            <tbody>
            {% if registro %}
                {% for i in registro %}
                    <tr class="tablesaw-sortable-arrow table-info">
                        <td>{{ i.id_llamada.nombre_solicitante }}</td>
                        <td>{{ i.id_llamada.ruta }}</td>
                        <td>{{ i.id_llamada.cantidad_pedido }}</td>
                        <td>{{ i.id_llamada.barrio }}</td>
                        <td>{{ i.id_llamada.localidad }}</td>
                        <td>{{ i.id_llamada.material }}</td>
                        <td>{{ i.id_llamada.nombre_destinatario }}</td>
                        <td>{{ i.id_llamada.telefono }}</td>
                        <td>{{ i.nombre_contesta }}</td>
                        <td>{{ i.fecha_entrega }}</td>
                        <td>{{ i.id_estado.nombre }}</td>
                        <td><a href="{{ i.id_grabacion.audio.url }}">{{ i.id_grabacion }}</a></td>
                    </tr>
                {% endfor %}
            {% endif %}
            {% if error %}
                <div class="alert alert-info">
                    <span class="glyphicon glyphicon-info-sign"></span> No hay llamadas!
                </div>
            {% endif %}
            </tbody>
        </table>
    </div>
    {% block javascript %}
        <script>
            $(document).ready(function () {
                $('#table').DataTable({
                    "scrollX": true,
                    "scrollY": "400px",
                    "scrollCollapse": true,
                    bfilter: false,
                    ordering: true,
                    searching: true,
                    info: false,
                    "language": espaniol
                });
            });

            function excel_exporte() {
                var wb = XLSX.utils.table_to_book(document.getElementById('table'), {sheet: "Sheet JS"});
                var wbout = XLSX.write(wb, {bookType: 'xlsx', bookSST: true, type: 'binary'});
                return wbout
            }


            function s2ab(s) {
                var buf = new ArrayBuffer(s.length);
                var view = new Uint8Array(buf);
                for (var i = 0; i < s.length; i++) view[i] = s.charCodeAt(i) & 0xFF;
                return buf;
            }

            $("#button-a").click(function () {

                Swal.fire({
                    title: 'Desea exportar los datos?',
                    text: "Verifique los datos de la tabla!",
                    icon: 'info',
                    showCancelButton: true,
                    confirmButtonColor: 'info',
                    cancelButtonColor: '#595d65',
                    confirmButtonText: 'Exportar!'
                }).then((result) => {
                    if (result.value) {
                        saveAs(new Blob([s2ab(excel_exporte())], {type: "application/octet-stream"}), 'Telemercadeo.xlsx');
                        Swal.fire(
                            'Exportado!',
                            'Su reporte esta listo',
                            'success'
                        )
                    }
                })
            });

            var espaniol = {
                "sProcessing": "Procesando...",
                "sLengthMenu": "Mostrar _MENU_ Registros",
                "sZeroRecords": "No se encontraron resultados",
                "sEmptyTable": "Ningún dato disponible en esta tabla",
                "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "sInfoThousands": ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst": "Primero",
                    "sLast": "Último",
                    "sNext": "Siguiente",
                    "sPrevious": "Anterior"
                },
                "oAria": {
                    "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                },
                "buttons": {
                    "copy": "Copiar",
                    "colvis": "Visibilidad"
                }
            };
        </script>
    {% endblock %}
{% endblock %}

templates/reportes/reporte_llamada.html
{% extends 'base/base.html' %}
{% load static %}
{{% block title %}
    <head>
        <link rel="icon" type="image/png" sizes="192x192" href="{% static 'dist/img/LogoSGT.png' %}">
        <title>Reporte de Llamadas</title>
        <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    </head>
{% endblock %}
{% block main %}


    <div class="container bg-white mt-2 cp">
        <strong class="d-flex justify-content-center m-1"><i class="fas fa-chart-bar mt-1"></i>&nbsp;Estadisticas de
            llamada</strong>
        <hr>
        <div class="row">
            <div class="col-sm-10">
                <canvas id="Grafica" width="65" height="40"></canvas>

                <div class="d-flex justify-content-center  p-3">

                    <select class="custom-select mr-sm-2" onchange="funcion(this.value)" name="respuesta">
                        <option value="0">Desde siempre</option>
                        <option value="1">Ultimo dia</option>
                        <option value="2">Ultima semana</option>
                        <option value="3">Ultimo mes</option>
                    </select>
                </div>
            </div>

        </div>
    </div>



    <script>

        function funcion(valor) {
            $.ajax({
                method: 'GET',
                url: '{% url 'archivo:llevar_reporte_llamada' %}',
                data: {
                    'valor': valor
                },
                success: function (data) {
                    dar(data);
                }
            });
        }

        Canvas = document.getElementById("Grafica").getContext('2d');
        var myChart = new Chart(Canvas, {
            type: "bar",
            data: {
                labels: ['Informacion de la entrega', 'No contesta', 'Aplaza', 'No cubre', 'Solicita almacen', 'Desiste', 'Almacen compromete', 'Datos errados', 'No sabe'],
                datasets: [{
                    label: 'Num datos',
                    data: [0, 0, 0, 0, 0, 0, 0, 0, 0],
                    backgroundColor: [
                        'rgb(66, 134, 244,0.5)',
                        'rgba(36,243,179,0.77)',
                        'rgba(83,229,105,0.87)',
                        'rgb(229, 89, 50,0.5)',
                        'rgb(229, 89, 50,0.5)',
                        'rgb(229,0,46)',
                        'rgb(229, 89, 50,0.5)',
                        'rgba(229,105,85,0.82)',
                        'rgb(229, 89, 50,0.5)',
                    ]
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });

        function dar(data) {
            myChart.data.datasets[0].data = [data.exito, data.no_contesta, data.CLAPLE, data.ZNCUB, data.CLEAL, data.CLDES, data.ALCOMPE, data.datos_errados, data.CLINOSOL];
            myChart.data.datasets[0].label = data.nombre;
            myChart.update();
        }
    </script>

    <style>
        .container {
            width: 65%;
            height: 70%;

        }


        .cp {
            border-radius: 3px;
            -webkit-box-shadow: 14px 9px 23px -6px rgba(0, 0, 0, 0.45);
            -moz-box-shadow: 14px 9px 23px -6px rgba(0, 0, 0, 0.45);
            box-shadow: 14px 9px 23px -6px rgba(0, 0, 0, 0.45);
        }
    </style>
{% endblock %}

templates/reportes/reporte_usuario.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}

    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'dist/img/LogoSGT.png' %}">
    <title>Reporte de usuario</title>
    <script src="{% static 'dist/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'dist/Datatables/FileSaver.min.js' %}"></script>
    <script src="{% static 'dist/Datatables/xlsx.full.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'dist/bootstrap/dist/css/bootstrap.min.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'dist/font animations.css' %}">



{% endblock %}

{% block main %}

    <div class="container bg-white mt-2 cp">
        <strong class="d-flex justify-content-center m-1"><i class="fas fa-chart-bar mt-1"></i>&nbsp;Estadisticas de
            usuario</strong>
        <hr>
        <div class="row">

            <div class="col-8">
                <canvas id="Grafica" width="38" height="30"></canvas>
            </div>
            <div class="col-4">
                <ul class="list-group mt-2">
                    <li class="list-group-item text-muted"><i class="fas fa-hand-holding-usd"></i> Ganancias</li>
                    <li class="list-group-item text-center">
                        <strong><i class="fas fa-coins faa-shake animated"></i> Total a pagar:
                            <span id="liquidacion" name="liquidacion"></span>
                        </strong>

                    </li>
                </ul>
            </div>
        </div>

        <div class="row card-footer">

            {# Este es el de las fechas #}
            <div class="col-sm">
                <strong>Rango de ejecucion </strong>
                <select class="custom-select mr-sm-2" name="fecha" id="fecha">
                    <option value="0">Desde siempre</option>
                    <option value="1">Ultimo dia</option>
                    <option value="2">Ultima semana</option>
                    <option value="3">Ultimo mes</option>
                </select>
            </div>

            {# Este es el de los usuario #}
            <div class="col-sm-5">
                <strong>Operador</strong>
                <select class="custom-select mr-sm-2 col-sm" name="usuario" id="usuario">
                    {% for a in usuario %}
                        <option value="{{ a.pk }}">{{ a.usuario.username }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-sm">
                <button type="button" class="btn btn-outline-info mt-4" onclick="funcion()"><i
                        class="fas fa-search"></i> Buscar
                </button>
            </div>
        </div>
    </div>



    <script>

        function funcion() {
            var usuario = document.getElementById('usuario').value;
            var valor = document.getElementById('fecha').value;
            $.ajax({
                method: 'GET',
                url: '{% url 'archivo:traer_reporte_usuario' %}',
                data: {
                    'valor': valor,
                    'usuario': usuario
                },
                success: function (data) {
                    $("#liquidacion").html(`$${data.liquidacion.suma}`);
                    dar(data);
                }
            });
        }

        Canvas = document.getElementById("Grafica").getContext('2d');
        var myChart = new Chart(Canvas, {
            type: "bar",
            data: {
                labels: ['Informacion de la entrega', 'No contesta', 'Aplaza', 'No cubre', 'Solicita almacen', 'Desiste', 'Almacen compromete', 'Datos errados', 'No sabe'],
                datasets: [{
                    label: 'Num datos',
                    data: [0, 0, 0, 0, 0, 0, 0, 0, 0],
                    backgroundColor: [
                        'rgb(66, 134, 244,0.5)',
                        'rgba(36,243,179,0.77)',
                        'rgba(83,229,105,0.87)',
                        'rgb(229, 89, 50,0.5)',
                        'rgb(229, 89, 50,0.5)',
                        'rgb(229,0,46)',
                        'rgb(229, 89, 50,0.5)',
                        'rgba(229,105,85,0.82)',
                        'rgb(229, 89, 50,0.5)',
                    ]
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });

        function dar(data) {
            myChart.data.datasets[0].data = [data.exito, data.no_contesta, data.CLAPLE, data.ZNCUB, data.CLEAL, data.CLDES, data.ALCOMPE, data.datos_errados, data.CLINOSOL];
            myChart.data.datasets[0].label = data.nombre;
            myChart.update();
        }
    </script>

    <style>
        .container {
            width: 65%;
            height: 70%;

        }


        .cp {
            border-radius: 3px;
            -webkit-box-shadow: 14px 9px 23px -6px rgba(0, 0, 0, 0.45);
            -moz-box-shadow: 14px 9px 23px -6px rgba(0, 0, 0, 0.45);
            box-shadow: 14px 9px 23px -6px rgba(0, 0, 0, 0.45);
        }
    </style>
{% endblock %}