SGT/urls.py
# Django
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import re_path
import notifications.urls
from django.urls import reverse_lazy

urlpatterns = [
                  path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
                  path('archivo/', include(('file.urls', 'file'), namespace='archivo')),
                  path('usuario/', include(('usuario.urls', 'usuario'), namespace='usuario')),
                  path('prueba',
                       TemplateView.as_view(template_name='prueba.html')
                       ),
                  path('reset/password_reset', PasswordResetView.as_view(
                      template_name='registration/password_reset_form.html',
                      email_template_name="registration/password_reset_email.html"),
                       name='password_reset'),
                  path('reset/password_reset_done',
                       PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
                       name='password_reset_done'),
                  re_path(r'^reset/(?P<uidb64>[0-9A-za-z_\-]+)/(?P<token>.+)/$',
                          PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
                          name='password_reset_confirm'),
                  path('reset/done',
                       PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
                       name='password_reset_complete')

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

file/urls.py
"""URL's de importe del archivo"""

# Django
from django.urls import path

# Views
import file.views as ImporteControl
from file import views

# Filtros

urlpatterns = [
    path(
        route='importe/',
        view=ImporteControl.upload_excel,
        name='importe'
    ),
    path(
        route='entregar/',
        view=views.ListarArchivo.as_view(),
        name='listar_llamada'
    ),
    path(
        route='asignar/',
        view=views.registro_llamada,
        name='asignar'
    ),
    path(
        route='realizar/',
        view=views.registro_llamada,
        name='registrar_llamada'
    ),
    path(
        route='buzon/',
        view=views.realizar_llamada,
        name='buzon'
    ),
    path(
        route='repartir/',
        view=views.repartir,
        name='repartir'
    ),
    path(
        route='enviar',
        view=views.enviarLlamadas,
        name='enviarLlamada'
    ),
    path(
        route='entregar_l/',
        view=views.entregar.as_view(),
        name='entregar_l'
    ),
    path(
        route='entrega',
        view=views.ver_Llamadas,
        name='entrega'
    ),
    path(
        route='eliminar',
        view=views.archivoLlamadas.as_view(),
        name='eliminar'
    ),
    path(
        route='borrar',
        view=views.eliminarArchivo,
        name='exterminar'
    ),
    path(
        route='traer',
        view=views.traer,
        name='traer'
    ),
    path(
        route='ListFile',
        view=views.search,
        name='ListFile'
    ),
    path(
        route='verllamadas',
        view=views.ver_Llamadas,
        name='borrar'
    ),
    path(
        route='prueballamadas',
        view=views.pruebas_llamadas,
        name='prueballamada'
    ),
    path(
        route='prueba/<int:number>/',
        view=views.realizar_llamada,
        name='prueba'
    ),
    path(
        route='listfile',
        view=views.ListFile,
        name='listFile'
    ),
    path(
        route='create_estado',
        view=views.CrearEstado.as_view(),
        name='estado'
    ),

    path(
        route='update_estado',
        view=views.ActualizarEstado.as_view(),
        name='UpdateEstado'

    ),

    # esta ruta me retorna solo un template "reporte llamadas"
    path(
        route='reporte_llamada/',
        view=views.reporte_llamada,
        name='reporte_llamada'
    ),
    # esta ruta solo es para llevarle lo solicitado a el template"reporte llamadas"
    path(
        route='llevar_reporte_llamada',
        view=views.traer_reporte_llamada,
        name='llevar_reporte_llamada'
    ),
    # esta ruta me lleva a el metodo donde se exporta para aceb
    path(
        route='completo',
        view=views.reporte_general,
        name='completo'
    ),
    # esta ruta me retorna los datos en el template "reporte general"
    path(
        route='envio_general',
        view=views.trer_reporte_general,
        name='envio_general'
    ),
    # esta ruta me retorna solo un template "reporte usuario"
    path(
        route='reporte_usuario',
        view=views.reporte_usuario,
        name='reporte_usuario'
    ),
    # esta ruta es para llevarle lo solicitado a el template"reporte usuario"
    path(
        route='traer_reporte_usuario',
        view=views.traer_reporte_usuario,
        name="traer_reporte_usuario"
    ),
    path(
        route='liquidacion_usuario',
        view=views.liquidacion_operador,
        name='liquidacion_usuario'
    ),
    path(
        route='llevar_liquidacion',
        view=views.llevar_liquidacion,
        name='llevar_liquidacion'
    )
]

file/models/archivo.py
from django.db import models
from utils.models import BaseModel

# Create your models here.
class LlamadasEntrantes(BaseModel, models.Model):

    nombre_solicitante = models.CharField(max_length=50)
    ident_fiscal = models.CharField(max_length=50)

    nombre_destinatario = models.CharField(max_length=50)
    direccion_des_mcia = models.CharField(max_length=50)

    telefono = models.CharField(max_length=50)
    telebox = models.CharField(max_length=50)

    zona_transporte = models.CharField(max_length=50)
    material = models.CharField(max_length=50)

    texto_breve_material = models.CharField(max_length=50)
    documento_ventas = models.CharField(max_length=50)

    entrega = models.CharField(max_length=50)
    num_pedido_cliente = models.CharField(max_length=50)

    cantidad_pedido = models.CharField(max_length=50)
    observaciones_inicial = models.CharField(max_length=255)

    denom_articulos = models.CharField(max_length=50)
    localidad = models.CharField(max_length=50)

    barrio = models.CharField(max_length=50)
    ruta = models.CharField(max_length=50)

    hora_inicio = models.CharField(max_length=50)
    hora_final = models.CharField(max_length=50)

templates/archivo/eliminar_archivo.html
{% extends 'base/base.html' %}
{% load static %}
<meta charset="UTF-8">

<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<script src='https://code.jquery.com/jquery-3.2.1.min.js'></script>
{% block title %}
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'dist/img/LogoSGT.png' %}">
    <title>Administrar archivo</title>
{% endblock %}

{% block main %}
    <div class="hk-pg-wrapper">
        <div class="container">
            <table class="table table-striped" id="Tablet">
                <thead>
                <tr>
                    <th scope="col">Nombre</th>
                    <th scope="col">Fecha</th>
                    <th scope="col">Accion</th>
                </tr>
                </thead>
                <tbody>
                {% if object_list %}
                    {% for i in object_list %}
                        <tr id="archivo-{{ i.pk }}">
                            <td>{{ i.nombre }}</td>
                            <td>{{ i.created }}</td>
                            <td>
                                <button class="btn btn-danger " onclick="eliminar({{ i.pk }}) ">
                                    <i class="fas fa-trash-alt"></i></button>
                            </td>
                        </tr>
                        </tbody>

                    {% endfor %}
                    </table>

                    </div>
                {% else %}
                    <div class="alert alert-info" role="alert">
                        <h4><span class="glyphicon glyphicon-exclamation-sign"></span> No
                            hay archivos!
                        </h4>
                    </div>
                {% endif %}

        <script>
            function eliminar(id) {
                const swalWithBootstrapButtons = Swal.mixin({
                    customClass: {
                        cancelButton: 'btn btn-danger',
                        confirmButton: 'btn btn-success'

                    },
                    buttonsStyling: true

                });

                swalWithBootstrapButtons.fire({
                    title: 'Estas seguro?',
                    text: "Desea eliminar el archivo?",
                    icon: 'info',
                    showCancelButton: true,

                    cancelButtonText: 'Cancelar',
                    confirmButtonText: 'Continuar',
                    reverseButtons: false
                }).then((result) => {
                    if (result.value) {
                        $.ajax({
                            url: '{% url "archivo:exterminar" %}',
                            data: {
                                'id': id,
                            },
                            dataType: 'json',
                            success: function (data) {
                                if (data.deleted) {
                                    $("#Tablet #archivo-" + id).remove();
                                    bueni();
                                }
                                if (!data.deleted) {
                                    mensaje();
                                }
                            }
                        });
                    } else if (
                        /* Read more about handling dismissals below */
                        result.dismiss === Swal.DismissReason.cancel
                    ) {
                        swalWithBootstrapButtons.fire(
                            'Cancelado',
                            'Tu archivo esta seguro',
                            'success'
                        )
                    }
                })
            }

            function mensaje() {
                Swal.fire({
                    icon: 'error',
                    title: 'Error',
                    text: 'Este archivo ya tiene llamadas repartidas!',

                })
            }

            function bueni() {
                Swal.fire(
                    'Operacion Realizada    !',
                    'Eliminado correctamente',
                    'success'
                )

            }
        </script>
    </div>
{% endblock %}

templates/archivo/fileimport.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'dist/img/LogoSGT.png' %}">
    <title>Importe</title>

{% endblock %}


{% block main %}
    <div class="container mt-4">
        <div class="container-fluid">

            <div class="card">
                <div class="card-body">
                    <h4 class="hk-pg-title card-title">
                    <span class="pg-title-icon">
                    </span><i class="fas fa-file-excel"></i>&nbsp;Importe de archivo
                    </h4>
                    <hr>
                    <div class="container">
                        <div class="custom-file col-md-6 ">
                            <form action="{% url 'archivo:importe' %}" method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-group">
                                    {{ form.archivo }}
                                </div>
                                <button class="btn btn-outline-success" id="btn" type="submit" data-toggle="tooltip"
                                        data-placement="bottom" title="Importar archivo excel!">
                                    Importar
                                </button>

                            </form>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>
<div class="hk-footer-wrap container">
        <footer class="footer">
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <p>Creado por<a href="https://hencework.com/" class="text-dark" target="_blank">La Gerencia</a>
                        © 2019</p>
                </div>
                <div class="col-md-6 col-sm-12">
                    <p class="d-inline-block">Follow us</p>
                    <a href="#" class="d-inline-block btn btn-icon btn-icon-only btn-indigo btn-icon-style-4"><span
                            class="btn-icon-wrap"><i class="fa fa-facebook"></i></span></a>
                    <a href="#" class="d-inline-block btn btn-icon btn-icon-only btn-indigo btn-icon-style-4"><span
                            class="btn-icon-wrap"><i class="fa fa-twitter"></i></span></a>
                    <a href="#" class="d-inline-block btn btn-icon btn-icon-only btn-indigo btn-icon-style-4"><span
                            class="btn-icon-wrap"><i class="fa fa-google-plus"></i></span></a>
                </div>
            </div>
        </footer>
    </div>

    <script>
        function papa() {
            debugger
            archivo = document.getElementById('nombre');
            otra = archivo.value;
            var extension = /(.xls|xlsx)$/i;
            if (!extension.exec(otra)) {
                document.getElementById('input').value = '';
                Swal.fire({
                    icon: 'error',
                    title: 'Error',
                    text: 'Solo se pueden extensiones de tipo .xlsx/.xls',
                });
                return false;
            }
        }
    </script>


{% endblock %}

templates/archivo/listar_archivo.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'dist/img/LogoSGT.png' %}">
    <title>Llamadas</title>

{% endblock %}
{% block main %}
    <div class="card-header mt-4">
        <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <ul class="list-group">
                        <li class="list-group-item text-muted"><i class="fa fa-dashboard fa-1x"></i> Actividad</li>
                        <li class="list-group-item text-right">
                        <span class="pull-left">
                            <strong><i class="fas fa-sort-numeric-up"></i> Cantidad</strong>
                        </span>&nbsp;
                            <span id="cant_ll">{{ llamadas_hoy|length }}</span>
                        </li>
                        <li class="list-group-item text-right" id="cant_usu">
                        <span class="pull-left">
                            <strong><i class="fa fa-user"></i>Usuarios</strong></span>&nbsp;
                            {{ usuario_conectado|length }}
                        </li>
                        <li class="list-group-item text-right">
                        <span class="pull-left">
                            <strong><i class="fas fa-sort-numeric-down-alt"></i> Restantes</strong>
                        </span>&nbsp;
                            <span id="llam_res"></span>
                        </li>
                        <li class="list-group-item text-right">
                        <span class="pull-left">
                            <strong><i class="far fa-hand-pointer"></i> Seleccionado</strong>
                        </span>&nbsp;
                            <span id="conteo"></span>
                        </li>
                        <li class="list-group-item text-right">
                        <span class="pull-left">
                            <strong><i class="fas fa-divide"></i> Division</strong>
                        </span>&nbsp;
                            <span id="division">
                        </span>
                        </li>
                        <a id="nea" href="{% url 'archivo:asignar' %}" hidden></a>
                    </ul>
                    <div class="d-flex justify-content-center mt-5">
                        <button class="btn btn-two faa-vertical animated-hover" id="clickes"><i class="fas fa-paper-plane"></i> Enviar</button>

                    </div>
                </div>
                <div class="col-sm">
                    <div class="col">
                        <p><i class="far fa-hand-pointer"></i> Seleccione las llamadas que desee:</p>
                        <div id="demo" onmouseup="unaFuncion()" class="row">
                            <div class="col-lg">
                                <div class="wrapper">
                                    <div id="wrapper">
                                        <div id="container">
                                            {% for llamada in llamadas_hoy %}
                                                <div class="box">
                                                    <span class="nota"
                                                          style="font-size: 60%">{{ llamada.ruta }}</span>
                                                    <p hidden>{{ llamada.id }}</p>
                                                </div>
                                            {% empty %}
                                                <div class="d-flex justify-content-center">
                                                    <div class="alert alert-info" role="alert">
                                                        <span class="glyphicon glyphicon-exclamation-sign  faa-burst animated"></span> No
                                                        hay llamadas para repartir!
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    {% include 'base/components/tablaUserConect.html' %}
                </div>
                <button class="openbtn" onclick="openNav()"><i class="fa fa-user faa-bounce animated-hover"></i>Usuarios en linea
                </button>
            </div>


        </div>

    </div>







    <!-- Footer -->
    <div class="hk-footer-wrap container">
        <footer class="footer">
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <p>Creado por<a href="https://hencework.com/" class="text-dark" target="_blank">La Gerencia</a>
                        © 2019</p>
                </div>
                <div class="col-md-6 col-sm-12">
                    <p class="d-inline-block">Follow us</p>
                    <a href="#" class="d-inline-block btn btn-icon btn-icon-only btn-indigo btn-icon-style-4"><span
                            class="btn-icon-wrap"><i class="fa fa-facebook"></i></span></a>
                    <a href="#" class="d-inline-block btn btn-icon btn-icon-only btn-indigo btn-icon-style-4"><span
                            class="btn-icon-wrap"><i class="fa fa-twitter"></i></span></a>
                    <a href="#" class="d-inline-block btn btn-icon btn-icon-only btn-indigo btn-icon-style-4"><span
                            class="btn-icon-wrap"><i class="fa fa-google-plus"></i></span></a>
                </div>
            </div>
        </footer>
    </div>

{% endblock %}
{% block scripts %}
    {{ block.super }}
    {% load static %}
    <script src="{% static 'dist/js/selectable/selectable.js' %}"></script>

    <script src="{% static 'dist/js/codigo.js' %}"></script>
    <script src="{% static 'dist/js/code.js' %}"></script>

    <script>
        var urlAsignar = document.getElementById('nea').getAttribute('href');
        var aux = document.location.href.substr(0, 21);
        var urlCompleta = aux + urlAsignar;

    </script>
{% endblock %}

templates/archivo/prueba.html
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>Document</title>
</head>
<body>


<div>
    <form action="{% url 'archivo:oe' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" id="input" name="input"
               accept="application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"/>

        <button type="submit">enviar</button>
</form>
    <div id="result"></div>
    <table id="grid1" >

    </table>

    <button onclick="alerta()">alertar</button>
</div>

{% load static %}
<script>
    function alerta() {
        alert('no funcionas')
    }
</script>

<script src="http://ajax.aspnetcdn.com/ajax/modernizr/modernizr-2.8.3.js"></script>
<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="http://code.jquery.com/ui/1.11.1/jquery-ui.min.js"></script>

<script type="text/javascript"
        src="http://cdn-na.infragistics.com/igniteui/2019.2/latest/js/infragistics.core.js"></script>
<script type="text/javascript"
        src="http://cdn-na.infragistics.com/igniteui/2019.2/latest/js/infragistics.lob.js"></script>

<script type="text/javascript"
        src="http://cdn-na.infragistics.com/igniteui/2019.2/latest/js/modules/infragistics.ext_core.js"></script>
<script type="text/javascript"
        src="http://cdn-na.infragistics.com/igniteui/2019.2/latest/js/modules/infragistics.ext_collections.js"></script>
<script type="text/javascript"
        src="http://cdn-na.infragistics.com/igniteui/2019.2/latest/js/modules/infragistics.ext_text.js"></script>
<script type="text/javascript"
        src="http://cdn-na.infragistics.com/igniteui/2019.2/latest/js/modules/infragistics.ext_io.js"></script>
<script type="text/javascript"
        src="http://cdn-na.infragistics.com/igniteui/2019.2/latest/js/modules/infragistics.ext_ui.js"></script>
<script type="text/javascript"
        src="http://cdn-na.infragistics.com/igniteui/2019.2/latest/js/modules/infragistics.documents.core_core.js"></script>
<script type="text/javascript"
        src="http://cdn-na.infragistics.com/igniteui/2019.2/latest/js/modules/infragistics.ext_collectionsextended.js"></script>
<script type="text/javascript"
        src="http://cdn-na.infragistics.com/igniteui/2019.2/latest/js/modules/infragistics.excel_core.js"></script>
<script type="text/javascript"
        src="http://cdn-na.infragistics.com/igniteui/2019.2/latest/js/modules/infragistics.ext_threading.js"></script>
<script type="text/javascript"
        src="http://cdn-na.infragistics.com/igniteui/2019.2/latest/js/modules/infragistics.ext_web.js"></script>
<script type="text/javascript"
        src="http://cdn-na.infragistics.com/igniteui/2019.2/latest/js/modules/infragistics.xml.js"></script>
<script type="text/javascript"
        src="http://cdn-na.infragistics.com/igniteui/2019.2/latest/js/modules/infragistics.documents.core_openxml.js"></script>
<script type="text/javascript"
        src="http://cdn-na.infragistics.com/igniteui/2019.2/latest/js/modules/infragistics.excel_serialization_openxml.js"></script>
<script src="{% static "dist/js/excel_upload.js" %}"></script>

</body>
</html>

templates/archivo/pueba.html
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>Document</title>
</head>
<body>


<div>
    <form action="{% url 'archivo:oe' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" id="input" name="input"
               accept="application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"/>

        <button type="submit">enviar</button>
</form>
    <div id="result"></div>
    <table id="grid1" >

    </table>

    <button onclick="alerta()">alertar</button>
</div>

{% load static %}
<script>
    function alerta() {
        alert('no funcionas')
    }
</script>

<script src="http://ajax.aspnetcdn.com/ajax/modernizr/modernizr-2.8.3.js"></script>
<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="http://code.jquery.com/ui/1.11.1/jquery-ui.min.js"></script>

<script type="text/javascript"
        src="http://cdn-na.infragistics.com/igniteui/2019.2/latest/js/infragistics.core.js"></script>
<script type="text/javascript"
        src="http://cdn-na.infragistics.com/igniteui/2019.2/latest/js/infragistics.lob.js"></script>

<script type="text/javascript"
        src="http://cdn-na.infragistics.com/igniteui/2019.2/latest/js/modules/infragistics.ext_core.js"></script>
<script type="text/javascript"
        src="http://cdn-na.infragistics.com/igniteui/2019.2/latest/js/modules/infragistics.ext_collections.js"></script>
<script type="text/javascript"
        src="http://cdn-na.infragistics.com/igniteui/2019.2/latest/js/modules/infragistics.ext_text.js"></script>
<script type="text/javascript"
        src="http://cdn-na.infragistics.com/igniteui/2019.2/latest/js/modules/infragistics.ext_io.js"></script>
<script type="text/javascript"
        src="http://cdn-na.infragistics.com/igniteui/2019.2/latest/js/modules/infragistics.ext_ui.js"></script>
<script type="text/javascript"
        src="http://cdn-na.infragistics.com/igniteui/2019.2/latest/js/modules/infragistics.documents.core_core.js"></script>
<script type="text/javascript"
        src="http://cdn-na.infragistics.com/igniteui/2019.2/latest/js/modules/infragistics.ext_collectionsextended.js"></script>
<script type="text/javascript"
        src="http://cdn-na.infragistics.com/igniteui/2019.2/latest/js/modules/infragistics.excel_core.js"></script>
<script type="text/javascript"
        src="http://cdn-na.infragistics.com/igniteui/2019.2/latest/js/modules/infragistics.ext_threading.js"></script>
<script type="text/javascript"
        src="http://cdn-na.infragistics.com/igniteui/2019.2/latest/js/modules/infragistics.ext_web.js"></script>
<script type="text/javascript"
        src="http://cdn-na.infragistics.com/igniteui/2019.2/latest/js/modules/infragistics.xml.js"></script>
<script type="text/javascript"
        src="http://cdn-na.infragistics.com/igniteui/2019.2/latest/js/modules/infragistics.documents.core_openxml.js"></script>
<script type="text/javascript"
        src="http://cdn-na.infragistics.com/igniteui/2019.2/latest/js/modules/infragistics.excel_serialization_openxml.js"></script>
<script src="{% static "dist/js/excel_upload.js" %}"></script>

</body>
</html>

templates/archivo/repartir.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'dist/img/LogoSGT.png' %}">
    <title>Asignar llamada</title>

{% endblock %}

{% block main %}

    <div class="hk-pg-wrapper">
        <div class="container">

            <div class="container-fluid">
                <div class="row mt-50">
                    <div class="col-md-8 offset-md-auto">
                        <div class="card" style="box-shadow: inset 0 0 20px #36876a">
                            <h5 class="card-header"><i class="far fa-share-square"></i> Entregar llamadas</h5>
                            <div class="card-body">

                                {% if llamadas %}


                                    <input name="cantidad" class="form-control col-xl-3" readonly
                                           onmousedown="return false" id="cantidad" value="{{ llamadas.count }}">

                                    <form name="formulario" id="formulario" method="post"
                                          action="{% url 'archivo:enviarLlamada' %}">

                                        <div class="col-md-9 mt-2">
                                            {% csrf_token %}
                                            {% for operador in operadores %}

                                                <div class="form-group">
                                                    <label class="form-group">{{ operador.usuario }}</label>
                                                    <input value="{{ operador.pk }}" name="usuario[]"
                                                           id="usuario" class="form-control col-xl-9">

                                                </div>
                                                <div class="form-group">
                                                    <input name="valor[]" class="form-control col-xl-3" id="valor">
                                                </div>
                                            {% endfor %}

                                            {{ operadores|length }}


                                            <button type="submit" class="btn"
                                                    style="background-color:#36876a;color: #fff1f1">
                                                enviar
                                            </button>

                                        </div>
                                    </form>
                                    </div>


                                {% endif %}
                            {% if error %}
                                {{ error }}
                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}