SGT/urls.py
# Django
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import re_path
import notifications.urls
from django.urls import reverse_lazy

urlpatterns = [
                  path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
                  path('archivo/', include(('file.urls', 'file'), namespace='archivo')),
                  path('usuario/', include(('usuario.urls', 'usuario'), namespace='usuario')),
                  path('prueba',
                       TemplateView.as_view(template_name='prueba.html')
                       ),
                  path('reset/password_reset', PasswordResetView.as_view(
                      template_name='registration/password_reset_form.html',
                      email_template_name="registration/password_reset_email.html"),
                       name='password_reset'),
                  path('reset/password_reset_done',
                       PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
                       name='password_reset_done'),
                  re_path(r'^reset/(?P<uidb64>[0-9A-za-z_\-]+)/(?P<token>.+)/$',
                          PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
                          name='password_reset_confirm'),
                  path('reset/done',
                       PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
                       name='password_reset_complete')

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

file/urls.py
"""URL's de importe del archivo"""

# Django
from django.urls import path

# Views
import file.views as ImporteControl
from file import views

# Filtros

urlpatterns = [
    path(
        route='importe/',
        view=ImporteControl.upload_excel,
        name='importe'
    ),
    path(
        route='entregar/',
        view=views.ListarArchivo.as_view(),
        name='listar_llamada'
    ),
    path(
        route='asignar/',
        view=views.registro_llamada,
        name='asignar'
    ),
    path(
        route='realizar/',
        view=views.registro_llamada,
        name='registrar_llamada'
    ),
    path(
        route='buzon/',
        view=views.realizar_llamada,
        name='buzon'
    ),
    path(
        route='repartir/',
        view=views.repartir,
        name='repartir'
    ),
    path(
        route='enviar',
        view=views.enviarLlamadas,
        name='enviarLlamada'
    ),
    path(
        route='entregar_l/',
        view=views.entregar.as_view(),
        name='entregar_l'
    ),
    path(
        route='entrega',
        view=views.ver_Llamadas,
        name='entrega'
    ),
    path(
        route='eliminar',
        view=views.archivoLlamadas.as_view(),
        name='eliminar'
    ),
    path(
        route='borrar',
        view=views.eliminarArchivo,
        name='exterminar'
    ),
    path(
        route='traer',
        view=views.traer,
        name='traer'
    ),
    path(
        route='ListFile',
        view=views.search,
        name='ListFile'
    ),
    path(
        route='verllamadas',
        view=views.ver_Llamadas,
        name='borrar'
    ),
    path(
        route='prueballamadas',
        view=views.pruebas_llamadas,
        name='prueballamada'
    ),
    path(
        route='prueba/<int:number>/',
        view=views.realizar_llamada,
        name='prueba'
    ),
    path(
        route='listfile',
        view=views.ListFile,
        name='listFile'
    ),
    path(
        route='create_estado',
        view=views.CrearEstado.as_view(),
        name='estado'
    ),

    path(
        route='update_estado',
        view=views.ActualizarEstado.as_view(),
        name='UpdateEstado'

    ),

    # esta ruta me retorna solo un template "reporte llamadas"
    path(
        route='reporte_llamada/',
        view=views.reporte_llamada,
        name='reporte_llamada'
    ),
    # esta ruta solo es para llevarle lo solicitado a el template"reporte llamadas"
    path(
        route='llevar_reporte_llamada',
        view=views.traer_reporte_llamada,
        name='llevar_reporte_llamada'
    ),
    # esta ruta me lleva a el metodo donde se exporta para aceb
    path(
        route='completo',
        view=views.reporte_general,
        name='completo'
    ),
    # esta ruta me retorna los datos en el template "reporte general"
    path(
        route='envio_general',
        view=views.trer_reporte_general,
        name='envio_general'
    ),
    # esta ruta me retorna solo un template "reporte usuario"
    path(
        route='reporte_usuario',
        view=views.reporte_usuario,
        name='reporte_usuario'
    ),
    # esta ruta es para llevarle lo solicitado a el template"reporte usuario"
    path(
        route='traer_reporte_usuario',
        view=views.traer_reporte_usuario,
        name="traer_reporte_usuario"
    ),
    path(
        route='liquidacion_usuario',
        view=views.liquidacion_operador,
        name='liquidacion_usuario'
    ),
    path(
        route='llevar_liquidacion',
        view=views.llevar_liquidacion,
        name='llevar_liquidacion'
    )
]

usuario/urls.py
from django.urls import path

from usuario import views

urlpatterns = [

    path(
        route='login/',
        view=views.LoginViewUsuario.as_view(),
        name='login'
    ),
    path(
        route='cambio-contrasena/',
        view=views.cambio_contrasena,
        name='cambio'
    ),
    path(
        route='logout/',
        view=views.logout_view,
        name='logout'
    ),

    path(
        route='registro/',
        view=views.UserCreateView,
        name='signup'
    ),
    path(
        route='listar/',
        view=views.ListarUsuario.as_view(),
        name='listar_usuario'
    ),
    path(
        route='perfil/',
        view=views.UpdateProfileView.as_view(),
        name='perfil'
    ),
    path(
        route='deshabilitar/',
        view=views.deshabilitar,
        name='desactivar'
    ),
    path(
        route='con/',
        view=views.conectado,
        name='conexion'
    ),
    path(
        route='dis/',
        view=views.desconectado,
        name='desconexion'
    ),
    path(
        route='actualizar',
        view=views.actualizarUsu.as_view(),
        name='actualizar'
    ),
    path(
        route='notichecked',
        view=views.notificaciones_checked,
        name='notichecked'
    ),
]

templates/base/components/scriptjs.html
<script type="text/javascript">
    function conectado() {
        return `<div id="conectado" class="sub-dropdown-menu show-on-hover">
                        <a href="#" class="dropdown-toggle dropdown-item no-caret"><i
                                class="zmdi zmdi-check text-success"></i>Conectado</a>
                        <div class="dropdown-menu open-left-side">
                            <a id="btn-conexion" class="dropdown-item" onclick="no_conexionsoski()">
                                <i class="dropdown-icon zmdi zmdi-minus-circle-outline text-danger"></i>
                                <span>No Conectado</span></a>
                            <input id="estado-a-cambiar" type="hidden" value="False">
                        </div>
                    </div>`
    }

    function no_conectado() {
        return `<div id="no-conectado" class="sub-dropdown-menu show-on-hover">
                            <a href="#" class="dropdown-toggle dropdown-item no-caret"><i
                                    class="zmdi zmdi-check text-danger"></i>No Conectado</a>
                            <div class="dropdown-menu open-left-side">
                                <a id="btn-conexion" class="dropdown-item" onclick="conexionsoski()"><i
                                        class="dropdown-icon zmdi zmdi-check text-success"></i><span>Conectado</span></a>
                                <input id="estado-a-cambiar" type="hidden" value="True">
                            </div>
                        </div>`
    }

    function conexionsoski() {
        console.log("oelo");
        $.get('{% url "usuario:conexion" %}', function (data) {
            document.getElementById("punt").className = "badge badge-success badge-indicator";
            document.getElementById("conexionsita").innerHTML = conectado();
        });
    }

    function no_conexionsoski() {
        console.log("oelo");
        $.get('{% url "usuario:desconexion" %}', function (data) {
            document.getElementById("punt").className = "badge badge-danger badge-indicator";
            document.getElementById("conexionsita").innerHTML = no_conectado();
        });
    }


</script>

templates/base/components/scripts.html
{% load static %}

<script src="{% static 'dist/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'dist/popper.js/dist/umd/popper.min.js' %}"></script>
<script src="{% static 'vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- Slimscroll JavaScript -->
<script src="{% static 'dist/js/jquery.slimscroll.js' %}"></script>
<!-- Fancy Dropdown JS -->
<script src="{% static 'dist/js/dropdown-bootstrap-extended.js' %}"></script>
<!-- FeatherIcons JavaScript -->
<script src="{% static 'dist/js/feather.min.js' %}"></script>
<!-- Toggles JavaScript -->
<script src="{% static 'vendors/jquery-toggles/toggles.min.js' %}"></script>
<script src="{% static 'dist/js/toggle-data.js' %}"></script>
<!-- Counter Animation JavaScript -->

<script src="{% static 'vendors/jquery.counterup/jquery.counterup.min.js' %}"></script>
<!-- Vector Maps JavaScript -->
<script src="{% static 'vendors/vectormap/jquery-jvectormap-2.0.3.min.js' %}"></script>
<script src="{% static 'vendors/vectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
<script src="{% static 'vendors/vectormap/jquery-jvectormap-de-merc.js' %}"></script>
<script src="{% static 'dist/js/vectormap-data.js' %}"></script>
<!-- Owl JavaScript -->
<script src="{% static 'vendors/owl.carousel/dist/owl.carousel.min.js' %}"></script>


<script src="{% static 'vendors/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'vendors/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'vendors/datatables.net-dt/js/dataTables.dataTables.min.js' %}"></script>
<script src="{% static 'vendors/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'vendors/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'vendors/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
<script src="{% static 'vendors/jszip/dist/jszip.min.js' %}"></script>


<script src="{% static 'vendors/apexcharts/dist/apexcharts.min.js' %}"></script>
<script src="{% static 'dist/js/irregular-data-series.js' %}"></script>
<!-- Init JavaScript -->
<script src="{% static 'dist/js/init.js' %}"></script>


<!--Validaciones JS -->
<script src="{% static 'dist/js/validaciones.js' %}"></script>
<!-- SweetAlert -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>


<!---iconos Font awesome---->
<script src="{% static 'dist/iconos_font_awesome.js' %}"></script>


<!--Calendar -->

<link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css"/>

<!--File import excel-->

<script src="{% static "dist/js/excel_upload.js" %}"></script>

templates/base/components/sidebar.html
{% load static %}
{% block sidebar %}
    <nav class="hk-nav hk-nav-dark bg-grey-dark-4">
        <a href="javascript:void(0);" id="hk_nav_close" class="hk-nav-close"><span class="feather-icon"><i
                data-feather="x"></i></span></a>
        <div class="nicescroll-bar">
            <div class="navbar-nav-wrap">
                <ul class="navbar-nav flex-column">
                    <li class="nav-item active">
                         <span class="nav-link-text"><img src="{% static 'dist/img/SGT.png' %}" width="200px"
                                                          srcset=""></span>
                        </a>

                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="javascript:void(0);" data-toggle="collapse" data-target="#dash_drp">
                            <i class="fas fa-headset"></i>
                            <span class="nav-link-text">Bandeja Entrada</span>
                        </a>
                        <ul id="dash_drp" class="nav flex-column collapse collapse-level-1">
                            <li class="nav-item">
                                <ul class="nav flex-column">
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'file:buzon' %}">Realizar llamada</a>
                                    </li>

                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>
                <hr class="nav-separator">
                <div class="nav-header">
                    <span>Opciones</span>
                    <span>SGT</span>
                </div>


                <ul class="navbar-nav flex-column">

                    {% if user.is_staff %}

                        <li class="nav-item">
                            <a class="nav-link" href="javascript:void(0);" data-toggle="collapse"
                               data-target="#Components_drp">
                                <i class="far fa-file-archive"></i>
                                <span class="nav-link-text">Archivo</span>
                            </a>
                            <ul id="Components_drp" class="nav flex-column collapse collapse-level-1">
                                <li class="nav-item">
                                    <ul class="nav flex-column">

                                        <li class="nav-item">
                                            <a class="nav-link" href="{% url 'archivo:importe' %}">Importa archivo</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="{% url 'archivo:listar_llamada' %}">Entregar
                                                llamadas</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="{% url 'archivo:eliminar' %}">Administrar
                                                archivo</a>
                                        </li>

                                    </ul>
                                </li>
                            </ul>
                        </li>



                        <li class="nav-item">
                            <a class="nav-link" href="javascript:void(0);" data-toggle="collapse"
                               data-target="#content_drp">
                                <i class="fas fa-poll"></i>
                                <span class="nav-link-text">Resultados</span>
                            </a>
                            <ul id="content_drp" class="nav flex-column collapse collapse-level-1">
                                <li class="nav-item">
                                    <ul class="nav flex-column">
                                        <li class="nav-item">
                                            <a class="nav-link" href="{% url 'archivo:completo' %}">Exportar
                                                archivos</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="{% url 'archivo:reporte_llamada' %}">Llamadas
                                                realizadas</a>
                                        </li>

                                        <li class="nav-item">
                                            <a class="nav-link" href="{% url 'archivo:reporte_usuario' %}">Reporte usuario</a>
                                        </li>

                                    </ul>

                                </li>
                            </ul>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="javascript:void(0);" data-toggle="collapse"
                           data-target="#utilities_drp">
                            <i class="fa fa-money-check-alt"></i>
                            <span class="nav-link-text">Liquidaciones</span>
                        </a>

                        <ul id="utilities_drp" class="nav flex-column collapse collapse-level-1">
                            <li class="nav-item">
                                <ul class="nav flex-column">
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'archivo:liquidacion_usuario' %}">Reportes</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>

                    </li>
                    {% if user.is_staff %}
                        <li class="nav-item">
                            <a class="nav-link" href="javascript:void(0);" data-toggle="collapse"
                               data-target="#forms_drp">
                                <i class="fa fa-user-alt"></i>
                                <span class="nav-link-text">Usuarios</span>
                            </a>
                            <ul id="forms_drp" class="nav flex-column collapse collapse-level-1">
                                <li class="nav-item">
                                    <ul class="nav flex-column">

                                        <li class="nav-item">
                                            <a class="nav-link"
                                               href="{% url 'usuario:listar_usuario' %}">Operadores</a>
                                        </li>

                                    </ul>
                                </li>
                            </ul>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

templates/base/components/tablaUserConect.html
<div id="mySidepanel" class="sidepanel">
    <a class="title-sidebar" style="color: #FFFFFF"><i class="fas fa-user-friends"></i> En linea
        <button class="btn btn-" id="cerrar" onclick="closeNav()">&times;</button>
    </a>
    <a>{% for usuario in usuario_conectado %}

        <ul>
            <li>
                <div id="hablalo" class="chat_people" style="cursor:pointer;">

                    <p hidden>{{ usuario.pk }}</p>
                    <div class="chat_ib">
                        <h5><span class="green led"></span>&nbsp;{{ usuario.usuario.get_username }} </h5>
                    </div>
                </div>
            </li>
        </ul>
    {% empty %}
        <div class="alert alert-info" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign"></span> No
            No hay usuarios en linea!
        </div>

    {% endfor %}
    </a>
</div>

<script>
    function openNav() {
        document.getElementById("mySidepanel").style.width = "250px";
    }

    function closeNav() {
        document.getElementById("mySidepanel").style.width = "0";
    }
</script>