SGT/urls.py
# Django
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import re_path
import notifications.urls
from django.urls import reverse_lazy

urlpatterns = [
                  path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
                  path('archivo/', include(('file.urls', 'file'), namespace='archivo')),
                  path('usuario/', include(('usuario.urls', 'usuario'), namespace='usuario')),
                  path('prueba',
                       TemplateView.as_view(template_name='prueba.html')
                       ),
                  path('reset/password_reset', PasswordResetView.as_view(
                      template_name='registration/password_reset_form.html',
                      email_template_name="registration/password_reset_email.html"),
                       name='password_reset'),
                  path('reset/password_reset_done',
                       PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
                       name='password_reset_done'),
                  re_path(r'^reset/(?P<uidb64>[0-9A-za-z_\-]+)/(?P<token>.+)/$',
                          PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
                          name='password_reset_confirm'),
                  path('reset/done',
                       PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
                       name='password_reset_complete')

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

file/urls.py
"""URL's de importe del archivo"""

# Django
from django.urls import path

# Views
import file.views as ImporteControl
from file import views

# Filtros

urlpatterns = [
    path(
        route='importe/',
        view=ImporteControl.upload_excel,
        name='importe'
    ),
    path(
        route='entregar/',
        view=views.ListarArchivo.as_view(),
        name='listar_llamada'
    ),
    path(
        route='asignar/',
        view=views.registro_llamada,
        name='asignar'
    ),
    path(
        route='realizar/',
        view=views.registro_llamada,
        name='registrar_llamada'
    ),
    path(
        route='buzon/',
        view=views.realizar_llamada,
        name='buzon'
    ),
    path(
        route='repartir/',
        view=views.repartir,
        name='repartir'
    ),
    path(
        route='enviar',
        view=views.enviarLlamadas,
        name='enviarLlamada'
    ),
    path(
        route='entregar_l/',
        view=views.entregar.as_view(),
        name='entregar_l'
    ),
    path(
        route='entrega',
        view=views.ver_Llamadas,
        name='entrega'
    ),
    path(
        route='eliminar',
        view=views.archivoLlamadas.as_view(),
        name='eliminar'
    ),
    path(
        route='borrar',
        view=views.eliminarArchivo,
        name='exterminar'
    ),
    path(
        route='traer',
        view=views.traer,
        name='traer'
    ),
    path(
        route='ListFile',
        view=views.search,
        name='ListFile'
    ),
    path(
        route='verllamadas',
        view=views.ver_Llamadas,
        name='borrar'
    ),
    path(
        route='prueballamadas',
        view=views.pruebas_llamadas,
        name='prueballamada'
    ),
    path(
        route='prueba/<int:number>/',
        view=views.realizar_llamada,
        name='prueba'
    ),
    path(
        route='listfile',
        view=views.ListFile,
        name='listFile'
    ),
    path(
        route='create_estado',
        view=views.CrearEstado.as_view(),
        name='estado'
    ),

    path(
        route='update_estado',
        view=views.ActualizarEstado.as_view(),
        name='UpdateEstado'

    ),

    # esta ruta me retorna solo un template "reporte llamadas"
    path(
        route='reporte_llamada/',
        view=views.reporte_llamada,
        name='reporte_llamada'
    ),
    # esta ruta solo es para llevarle lo solicitado a el template"reporte llamadas"
    path(
        route='llevar_reporte_llamada',
        view=views.traer_reporte_llamada,
        name='llevar_reporte_llamada'
    ),
    # esta ruta me lleva a el metodo donde se exporta para aceb
    path(
        route='completo',
        view=views.reporte_general,
        name='completo'
    ),
    # esta ruta me retorna los datos en el template "reporte general"
    path(
        route='envio_general',
        view=views.trer_reporte_general,
        name='envio_general'
    ),
    # esta ruta me retorna solo un template "reporte usuario"
    path(
        route='reporte_usuario',
        view=views.reporte_usuario,
        name='reporte_usuario'
    ),
    # esta ruta es para llevarle lo solicitado a el template"reporte usuario"
    path(
        route='traer_reporte_usuario',
        view=views.traer_reporte_usuario,
        name="traer_reporte_usuario"
    ),
    path(
        route='liquidacion_usuario',
        view=views.liquidacion_operador,
        name='liquidacion_usuario'
    ),
    path(
        route='llevar_liquidacion',
        view=views.llevar_liquidacion,
        name='llevar_liquidacion'
    )
]

usuario/urls.py
from django.urls import path

from usuario import views

urlpatterns = [

    path(
        route='login/',
        view=views.LoginViewUsuario.as_view(),
        name='login'
    ),
    path(
        route='cambio-contrasena/',
        view=views.cambio_contrasena,
        name='cambio'
    ),
    path(
        route='logout/',
        view=views.logout_view,
        name='logout'
    ),

    path(
        route='registro/',
        view=views.UserCreateView,
        name='signup'
    ),
    path(
        route='listar/',
        view=views.ListarUsuario.as_view(),
        name='listar_usuario'
    ),
    path(
        route='perfil/',
        view=views.UpdateProfileView.as_view(),
        name='perfil'
    ),
    path(
        route='deshabilitar/',
        view=views.deshabilitar,
        name='desactivar'
    ),
    path(
        route='con/',
        view=views.conectado,
        name='conexion'
    ),
    path(
        route='dis/',
        view=views.desconectado,
        name='desconexion'
    ),
    path(
        route='actualizar',
        view=views.actualizarUsu.as_view(),
        name='actualizar'
    ),
    path(
        route='notichecked',
        view=views.notificaciones_checked,
        name='notichecked'
    ),
]

templates/users/creacion_perfil.html
<div class="modal-content" id="form" style="border-color:#36876a">
    <div class="modal-header">
        <h5 class="modal-title"><i class="fa fa-user"></i> Registro de usuario</h5>
        <button type="button" class="close" data-dismiss="modal"
                aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    <div class="container">
        <form id="insert" class="needs-validation"
              novalidate
              autocomplete="off" method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col form-group">
                    <label for="validationTooltip07">Cedula</label>
                    {{ form.cedula }}

                    <div class="invalid-tooltip">
                        Ingrese la cedula
                    </div>
                    <div class="valid-tooltip">
                        Bien hecho!
                    </div>
                </div>
                <div class="col form-group">

                    <label for="validationTooltipUsername">Email</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="validationTooltipUsernamePrepend">@</span>
                        </div>
                        {# INPUT #}
                        {{ form.email }}
                        <div class="invalid-tooltip">
                            Ingrese el email
                        </div>
                        <div class="valid-tooltip">
                            Bien hecho!
                        </div>
                    </div>
                </div>
            </div>

            <div class="row mt-3">
                <div class="col">
                    <label for="validationTooltip01">Nombres</label>
                    <input type="text" name="first_name" class="form-control"
                           id="validationTooltip01"
                           placeholder="Nombres" required="" onkeypress="return soloLetras(event)"
                           maxlength="50"
                           minlength="2" data-toggle="tooltip" title="">
                    <div class="valid-tooltip">
                        Bien hecho!
                    </div>
                    <div class="invalid-tooltip">
                        Ingrese el nombre
                    </div>

                </div>
                <div class="col">

                    <label for="validationTooltip02">Apellidos</label>
                    {# INPUT #}
                    <input type="text" name="last_name" class="form-control"
                           id="validationTooltip02"
                           placeholder="Apellidos" required="" onkeypress="return soloLetras(event)"
                           maxlength="50"
                           minlength="2">

                    <div class="valid-tooltip">
                        Bien hecho!
                    </div>
                    <div class="invalid-tooltip">
                        Ingrese el apellido
                    </div>
                </div>
                <div class="col">
                    <label for="validationTooltip03">Nombre de
                        usuario</label>
                    {{ form.username }}
                    <div class="invalid-tooltip">
                        Ingrese el nombre de usuario
                    </div>
                    <div class="valid-tooltip">
                        Bien hecho!
                    </div>
                </div>
            </div>
            <div class="row mt-5">
                <div class="col">
                    <label for="validationTooltip04">Contraseña</label>
                    {# INPUT #}
                    {{ form.password }}
                    <div id="Prism2" class="invalid-tooltip">
                    </div>
                    <div class="valid-tooltip">
                        Bien hecho!
                    </div>
                </div>
                <div class="col">
                    <label for="validationTooltip05">Confirmar
                        contraseña</label>
                    {{ form.password_confirmation }}
                    <div id="Prism" class="invalid-tooltip">
                    </div>
                    <div class="valid-tooltip">
                        Bien hecho!
                    </div>
                </div>
                <div class="col-sm">
                    <label for="Cargo">Tipo de usuario</label>
                    {{ form.is_staff }}
                </div>
            </div>

            <div class="modal-footer mt-5">
                <div id="Okey"></div>

                <button class="btn btn-info"
                        id="submit"
                        type="submit">Enviar
                </button>
                <button type="button" class="btn btn-secondary"
                        data-dismiss="modal">Cancelar
                </button>
            </div>


        </form>
        <div id="lock-modal"></div>
        <div id="loading-circle"></div>

    </div>
</div>
<style>
    #lock-modal {
        display: none;
        background-color: black;
        opacity: 0.6;
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        border-radius: inherit;
    }

    #loading-circle {
        display: none;
        position: absolute;
        top: 0;
        bottom: 0;
        left: 0;
        right: 0;
        margin: auto;
        width: 40px;
        height: 40px;
        border: 4px solid #f3f3f3;
        border-top: 4px solid #3498db;
        border-radius: 50%;
        animation: spin 0.6s ease-in infinite;
    }

    @keyframes spin {
        0% {
            transform: rotate(0deg);
        }
        100% {
            transform: rotate(360deg);
        }
    }
</style>

templates/users/login.html
{% extends "base/baselogin.html" %}
{% block head_content %}
    <title>Iniciar Sesion</title>
{% endblock %}
{% load static %}
{% block container %}
    {{ block.super }}

    <form id="Login" action="{% url 'usuario:login' %}" method="POST" autocomplete="off">
        {% csrf_token %}
        <div class="login-logo">
            <img src="{% static 'dist/img/LogoSGT.png' %}" alt="" srcset="">
        </div>

        <h3>
            <i class="fas fa-users"></i>INGRESAR
        </h3>

        <div class="form-group">
            <input type="text" class="form-control" placeholder="Nombre usuario" name="username" value=""/>
        </div>
        <div class="form-group">
            <input type="password" class="form-control" placeholder="Contraseña" name="password" value=""/>
        </div>
        <div class="form-group">
            <input type="submit" class="btnSubmit" value="Iniciar Sesion"/>
        </div>
        <div class="form-group">

            <a href="{% url 'password_reset' %}" class="btnForgetPwd" value="Login">Olvido su contraseña?</a>
        </div>
    </form>
{% endblock %}
{% block scriptsjs %}


    {% if form.errors %}
        <script>
        const ErrorNotification = window.createNotification({
            theme: 'error',
            showDuration: 5000
        });
        {% for field in form %}
            {% if field.errors %}
                ErrorNotification({
                    message: '{{ field.label }}: {{ field.errors|striptags }},{{ form.non_field_errors }}'
                });
            {% endif %}
        {% endfor %}

    {% endif %}
{% if form.errors %}
    ErrorNotification({
        message: '{{ form.non_field_errors|striptags }}'
    });
    </script>
{% endif %}

{% endblock %}

templates/users/nuevaContrasena.html
{% load static %}
{% block title %}
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'dist/img/LogoSGT.png' %}">
    <title>{{ perfil.usuario.first_name }}</title>
    <link href="{% static 'dist/css/style.css' %}" rel="stylesheet" type="text/css">
{% endblock %}
{% block main %}

    <div class="hk-pg-wrapper hk-auth-wrapper">
        <header class="d-flex justify-content-end align-items-center">
        </header>
        <div class="container-fluid">

            <div class="auth-form-wrap pt-xl-0 pt-70">
                <div class="auth-form w-xl-30 w-sm-50 w-100">
                    <a class="auth-brand text-center d-block mb-20" href="#">
                        <img class="" src="{% static 'dist/img/LogoSGT.png' %}" height="150" size="90"/>
                    </a>
                    <form method="post">
                        {% csrf_token %}
                        <h2 class="display-5 mb-10 text-center">Modificar Contraseña</h2>

                        <div class="form-group">
                            {{ form }}
                        </div>
                        <button class="btn  btn-block mb-20" style="background-color:#36876a;color: white"
                                type="submit">
                            Cambiar contraseña
                        </button>

                        <p class="text-right"><a href="{% url 'usuario:login' %}">Regresar</a>
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script>

    </script>
{% endblock %}

templates/users/perfil.html
{% load static %}
<head>
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'dist/img/LogoSGT.png' %}">
    <title>Configuracion</title>
    <link rel="stylesheet" href="{% static 'dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'dist/notifications.css' %}">
</head>
<body>
{% block form %}
    <form method="POST" action="{% url 'usuario:perfil' %}" name="perfilform" id="perfilform"
          enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container mt-5">
            <div class="card">
                <div class="card-title ml-2 mt-2">
                    {% if request.var %}

                        <h3><i class="fas fa-user-cog"></i> Complete los siguientes campos para continuar
                            <a id="atras" href="{% url 'usuario:logout' %}"
                               class="btn btn-info"
                               data-toggle="tooltip" data-placement="right" title="Regresar"><i
                                    class="fas fa-undo-alt"></i></a>
                        </h3>
                    {% else %}
                        <h3><i class="fas fa-user-cog"></i> {{ user }}
                            <a id="atras" href="{% url 'archivo:buzon' %}"
                               class="btn btn-info"
                               data-toggle="tooltip" data-placement="right" title="Regresar"><i
                                    class="fas fa-undo-alt"></i></a>
                        </h3>
                    {% endif %}


                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3 "><!--left col-->
                        <div class="text-center" style="margin-left: 10px">
                            {% if perfil.foto %}
                                <img src="{{ perfil.foto.url }}" class="avatar img-circle img-thumbnail"
                                     alt="avatar">
                            {% else %}
                                <img src="{% static 'dist/img/avatar1.jpg' %}"
                                     class="rounded-circle" width="130px" height="130px"/>
                            {% endif %}

                            <div class="upload-btn-wrapper m-2">
                                <button class="btn-1">Subir foto</button>
                                <input type="file" value="{{ perfil.foto }}" style="width:180px" name="foto" id="foto">

                            </div>
                        </div>
                    </div><!--/col-3-->

                    <div class="tab-content">
                        <div class="tab-pane active" id="home">
                            <div class="container">
                                <div class="row">
                                    <div class="col-sm-5">
                                        <div class="form-group " id="document-form">
                                            <label for="cedula  ">Cedula</label>
                                            <input class="form-control"
                                                   id="cedula" name="cedula"
                                                   maxlength="10"
                                                   value="{{ perfil.cedula }}"
                                                   placeholder="Documento de identidad"
                                                   type="text"/>
                                        </div>
                                    </div>
                                    <div class="col-sm-7">
                                        <div class="col">
                                            <label>Nombres</label>
                                            <input class="form-control"
                                                   readonly onmousedown="return false"
                                                   name="firts_name" id="firts_name"
                                                   maxlength="15"
                                                   required
                                                   value="{{ user.first_name }}"
                                                   type="text"/>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="container">
                                <div class="row">
                                    <div class="col">
                                        <label>Apellido</label>
                                        <input
                                                class="form-control"
                                                type="text"
                                                name="last_name"
                                                placeholder="Apellidos"
                                                required
                                                readonly
                                                value="{{ user.last_name }}"/>
                                    </div>
                                    <div class="col-sm">
                                        <div class="form-group">
                                            <label>Celular </label>
                                            <div class="form-group">
                                                <input class="form-control"
                                                       name="celular" id="celular"
                                                       placeholder="Movil"
                                                       maxlength="15" minlength="8"
                                                       value="{{ perfil.celular }}"
                                                       type="text"/>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-sm">

                                        <div class="form-group">
                                            <label>Telefono fijo </label>
                                            <input class="form-control"
                                                   name="telefono_fijo" id="telefono_fijo"
                                                   placeholder="Telefono fijo"
                                                   value="{{ perfil.telefono_fijo }}"
                                                   required
                                                   type="text"/>

                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="container">
                                <div class="row">
                                    <div class="col-sm">
                                        <div class="form-group">
                                            <label>Email</label>
                                            <input
                                                    class="form-control"
                                                    type="text"
                                                    name="email"
                                                    placeholder=""
                                                    required
                                                    readonly
                                                    value="{{ user.email }}"/>
                                        </div>
                                    </div>
                                    <div class="col-sm">
                                        <div class="form-group">
                                            <label>Celular telemercadeo </label>
                                            <div class="form-group">
                                                <input class="form-control"
                                                       name="celular_telemercadeo" id="celular_telemercadeo"
                                                       maxlength="15" minlength="8"
                                                       placeholder="Movil telemercadeo"
                                                       type="text"
                                                       value="{{ perfil.celular_telemercadeo }}"/>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="d-flex justify-content-around mt-5">

                                    <img src="{% static 'dist/img/LogoSGT.png' %}" height="80" class="fixed-bottom">
                                    <button type="submit" class="btn btn-success">Guardar cambios</button>
                                    <a class="btn btn-dark" href="{% url 'usuario:cambio' %}">Cambiar contraseña</a>
                                    <span style="color: gray;font-size: 13px">Ultima modificacion {{ perfil.modified }}</span>

                                </div>
                                <hr>
                            </div>
    </form>

    <!--/tab-pane-->





{% endblock %}
</body>
{% block javascript %}

    <script src="{% static 'dist/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'dist/popper.js/dist/umd/popper.min.js' %}"></script>
    <script src="{% static 'dist/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'dist/notifications.js' %}"></script>
    <script src="{% static 'dist/iconos_font_awesome.js' %}"></script>


    <script>
        const successNotification = window.createNotification({
            theme: 'success',
            showDuration: 5000
        });
        const ErrorNotification = window.createNotification({
            theme: 'error',
            showDuration: 5000
        });
        {% if form.errors %}
            {% for field in form %}
                {% if field.errors %}
                    ErrorNotification({
                        message: ' {{ field.label }}: {{ field.errors|striptags }}, {{ form.non_field_errors }}'
                    });
                {% endif %}
            {% endfor %}
        {% endif %}
        {% if messages %}
            {% for message in messages %}
                successNotification({
                    message: '{{ message }}'
                });
            {% endfor %}
        {% endif %}

        window.addEventListener('load', function () {
            document.querySelector('input[type="file"]').addEventListener('change', function () {

                if (this.files && this.files[0]) {
                    let img = document.querySelector('img');
                    img.src = URL.createObjectURL(this.files[0]);
                    successNotification({
                        message: 'Foto importada con exito!'
                    });

                }
            })
        });

        function setInputFilter(textbox, inputFilter) {
            ["input", "keydown", "keyup", "mousedown", "mouseup", "select", "contextmenu", "drop"].forEach(function (event) {
                textbox.addEventListener(event, function () {
                    if (inputFilter(this.value)) {
                        this.oldValue = this.value;
                        this.oldSelectionStart = this.selectionStart;
                        this.oldSelectionEnd = this.selectionEnd;

                    } else if (this.hasOwnProperty("oldValue")) {
                        this.value = this.oldValue;
                        this.setSelectionRange(this.oldSelectionStart, this.oldSelectionEnd);
                    } else {
                        this.value = "";
                    }
                });
            });
        }


        setInputFilter(document.getElementById("telefono_fijo"), function (value) {
            return /^-?\d*[.,]?\d*$/.test(value);
        });
        setInputFilter(document.getElementById("cedula"), function (value) {
            return /^-?\d*[.,]?\d*$/.test(value);
        });
        setInputFilter(document.getElementById("celular"), function (value) {
            return /^-?\d*[.,]?\d*$/.test(value);
        });
        setInputFilter(document.getElementById("celular_telemercadeo"), function (value) {
            return /^-?\d*[.,]?\d*$/.test(value);
        });


    </script>
{% endblock %}
<style>

    body {
        background-image: url("{% static 'dist/img/Mojito.jpg' %}");
    }

    .upload-btn-wrapper {
        position: relative;
        overflow: hidden;
        display: inline-block;

    }

    .btn-1 {
        border: 2px solid gray;
        color: gray;
        background-color: white;
        padding: 8px 20px;
        border-radius: 8px;
        font-size: 20px;
        font-weight: bold;

    }

    .upload-btn-wrapper input[type=file] {
        font-size: 100px;
        position: absolute;
        left: 0;
        top: 0;
        opacity: 0;

    }

    .card {
        background: black;
        color: #FFFFFF;
        opacity: 0.9;
        border-color: #0b2e13;
        border-radius: 10px;
    }

    hr {
        border: 1px solid #fff1f1;
    }

    #atras {
        margin-left: 83%;
    }
</style>